### ISSUE TITLE
error converting to gpx files

### ISSUE THREAD

**Issue by ar4121** [jantman/pizero-gpslog#2]
I haven't used it much, but about 50% of the time, I get an error while trying to convert the json file to gpx.  
They appear similar to the following:
`Unable to decode JSON on line 404; skipping. (ERROR: Expecting value: line 1 column 1 (char 0))
Exception loading line 1:
Traceback (most recent call last):
  File "/usr/local/bin/pizero-gpslog-convert", line 11, in <module>
    load_entry_point('pizero-gpslog', 'console_scripts', 'pizero-gpslog-convert')()
  File "/opt/GPS/pizero-gpslog/pizero_gpslog/converter.py", line 189, in main
    stats=args.stats
  File "/opt/GPS/pizero-gpslog/pizero_gpslog/converter.py", line 82, in convert
    gpx = self._gpx_for_logs(logs)
  File "/opt/GPS/pizero-gpslog/pizero_gpslog/converter.py", line 127, in _gpx_for_logs
    elevation=tpv['alt'],
KeyError: 'alt'
`

I haven't been able to dig into this yet, but I thought I would see if you have seen something similar to this.  

I'm unable to upload a file directly into here, github seems to not want to process that file.  I'm guessing this is likely the issue with being able to parse through the json file.  Here is the link to the file: 
EDITED
I've set it to expire in a week, as I haven't obfuscated anything in the file yet.  It would only open with emacs or vim, using a conventional editor like geany or gedit failed.  I'll try to get a logfile, I might just reinstall it using either info or debug.  

Device: Raspberry Pi 3
GPS: Globalsat BU 353 (not version 4, the previous generation)
Not using LED's yet, so it is using the fake LED code.

Thanks

**Comment by jantman** [comment]
Ok, there's two things going on here and two separate errors.

The first one is something I'm familiar with: ``Unable to decode JSON on line 404; skipping. (ERROR: Expecting value: line 1 column 1 (char 0))``. That's completely benign as it says "skipping"; this is because the last line in the file is corrupted binary garbage, likely because pizero-gpslog was writing to the file when the Pi was powered off. I routinely get that same issue, and it doesn't prevent anything from working right.

The second one, however, __is__ a problem:

```
Exception loading line 1:
Traceback (most recent call last):
  File "/home/jantman/GIT/pizero-gpslog/bin/pizero-gpslog-convert", line 11, in <module>
    load_entry_point('pizero-gpslog', 'console_scripts', 'pizero-gpslog-convert')()
  File "/home/jantman/GIT/pizero-gpslog/pizero_gpslog/converter.py", line 189, in main
    stats=args.stats
  File "/home/jantman/GIT/pizero-gpslog/pizero_gpslog/converter.py", line 82, in convert
    gpx = self._gpx_for_logs(logs)
  File "/home/jantman/GIT/pizero-gpslog/pizero_gpslog/converter.py", line 127, in _gpx_for_logs
    elevation=tpv['alt'],
KeyError: 'alt'
```

That seems to indicate that the first line of output (first position fix) is missing the altitude from its TPV (time-position-velocity) report. And, sure enough, it is missing the altitude measurement from (as far as I can tell) just that one first report.

I've just pushed a new version, 0.1.2, that contains a fix for this and converts your JSON properly. Please let me know if that works for you, and if there's anything else outstanding or whether I can close this.

-Jason

**Comment by ar4121** [comment]
OK,
So far so good.  I thought it had to with the alt, but I most of them seemed to have data.  I'll continue to try it and comment again tomorrow or monday, before about 50% of the json logs would convert, and the others would not.

Thanks again, much appreciated.

**Comment by jantman** [comment]
Sure, happy to help and happy that someone else might find this little bit of code useful!

**Comment by ar4121** [comment]
Great work, I've tried 6 different json files so far, all have had no problems.  You can go ahead and close this out.  

Thanks again, most of these gpx files I upload directly to OSM, so this frees up my garmin to be used as an actual map, though I will at some point try to write a little script that stops recording within a certain radius of certain points (like my house), to prevent me from having to manually edit and remove them in the gpx files themselves before being uploaded to their database.  

Thanks again!!!

**Comment by jantman** [comment]
Ok, glad it worked!

Sure!
